
default_stages: [commit, push]
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      args: [
        --line-length=80, 
        --target-version=py310
      ]
      exclude: ^(venv/|docs/)
      types: ['python']
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: [
        --max-line-length=80
      ]
      exclude: ^(venv/|docs/)
      types: ['python']
